### ISSUE TITLE
Entities Module - Include raw entity data

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#106]
Sample:

```
{
  "Accounts": [
    {
      "userPrincipalName": "user@contoso.com",
      "id": "186a8e5b-448d-400e-b306-84d8e551e93e",
      "onPremisesSecurityIdentifier": null,
      "onPremisesDistinguishedName": null,
      "onPremisesDomainName": null,
      "onPremisesSamAccountName": null,
      "onPremisesSyncEnabled": null,
      "mail": "user@contoso.com",
      "city": "Toronto",
      "state": "ON",
      "country": "CA",
      "department": "Department",
      "jobTitle": "Cloud Title",
      "officeLocation": null,
      "accountEnabled": true,
      "AssignedRoles": [],
      "RawEntity": []
    }
  ],
  "AccountsAllEnriched": true,
  "AccountsInput": 2,
  "AccountsEnriched": 2,
}
```

**Comment by piaudonn** [comment]
While at it, maybe we can do hostname? so far, just pass as-is, later maybe adding info such as AadDeviceId

**Comment by briandelmsft** [comment]
@piaudonn you can try the version now in 66341bc as well as the new return schema in the same branch.  This version now won't drop the account entity if enrichment fails and will return RawEntity data only for those entities.

I don't believe there's a path where host entities would be dropped, but RawEntity data was added there as well.  In the IP path there is a situation with an IP would be dropped, if Geo Enrichment is selected and Geo Enrichment fails the IP entity would presently be dropped.

**Comment by piaudonn** [comment]
@briandelmsft beautiful :) works great, parsing in the module was easy too with the operator I can't pronounce.

Note that since the input is no longer only entities but also a bunf of metadata, shall we call it EnrichedInput instead of Entities?

**Comment by briandelmsft** [comment]
@piaudonn i agree I think a rename is in order... Enrich-Input is pretty good... i think i'll also move it out of the /Shared and we'll just call this a module since at this point it could potentially stand on its own

**Comment by piaudonn** [comment]
@briandelmsft can you pass through the File entity? My FileInisght module works but need to use the Entnties from the incident trigger instead of the EnrichedEntities.

**Comment by briandelmsft** [comment]
will do, also will pass through domain and URL entities since those would likely be needed at some point

**Comment by briandelmsft** [comment]
@piaudonn 1780763 contains (untested) support for file, filehash, url and dns domain entity types... RawEntity data only, no enrichment
