### ISSUE TITLE
Generic KQL Module

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#121]
A generic module that accepts KQL query + entities as an input executes the query against Log analytics or M365 advanced Hunt API and returns result count and result count per entity.  

Will include some placeholder syntax that will be replaced at runtime by the module.  For example if you put {UPN} into the module call it will be replaced by the module at runtime with the data from the enriched entities.

**Comment by briandelmsft** [comment]
@piaudonn thoughts?

**Comment by piaudonn** [comment]
Like a wrapper for KQL? Interresting. 
I like the idea. that would be interresting to have examples of situations when to use it. Maybe when custom tables are involved? Or scenario with Defender tables? If the scenarios are already known, then we can have an "actual" module for it.
But anyways, I am in :) I don't find current ways to query LA or Defender table super ergonomic today.

**Comment by briandelmsft** [comment]
Exactly if the scenarios are common enough we'll just build it into a module but for more custom stuff then we have this KQL module.   That will still make things easier but allow for custom logic to be easily incorporated into our framework

**Comment by briandelmsft** [comment]
@piaudonn if you get a chance take a look at https://github.com/briandelmsft/SentinelAutomationModules/tree/kql_module/Modules/KQLModule

There's instructions on how to use the entity data to build your query in the readme... so far only the Sentinel query is setup so don't try to M365.  I wanted to get some thoughts from you on how it works before I added that to it.
