### ISSUE TITLE
safe IPs not matching

### ISSUE THREAD

**Issue by bobsyourmom** [briandelmsft/SentinelAutomationModules#130]
when I tried your playbook it was failing so I changed the last function to:
length('Body')
Then it was properly matching false when the IP wasn't matched.

**Comment by briandelmsft** [comment]
Thanks for letting us know.  Can you please clarify which module (playbook) the change was made in?  And what was the title of the step within that playbook?

**Comment by briandelmsft** [comment]
Do you have any further details on the issue to share?
