### ISSUE TITLE
Get-OOFDetails fails consistently 

### ISSUE THREAD

**Issue by piaudonn** [briandelmsft/SentinelAutomationModules#137]
This is what I always get as soon a I have one error in the loop:

![image](https://user-images.githubusercontent.com/22434561/143050613-52cce9b4-8138-4194-8dc4-1951c1965218.png)

Changing the "Run after condition" for the three "Filter array" operation fixes the issue but I am not sure if there's in fact not something else missing.

**Comment by piaudonn** [comment]
I am using the one deployed by the general [Deploy](https://github.com/briandelmsft/SentinelAutomationModules/blob/main/Deploy/azuredeploy.json) ARM template.

**Comment by briandelmsft** [comment]
Issues are when the entity can't be resolved by the base module (typically because it doesn't exist in AAD) or because the user has no mailbox.  Will fix both in the next update to ensure the results are returned even if these problems occur.
