### ISSUE TITLE
Use Bing Maps API to enrich comments and emails with maps

### ISSUE THREAD

**Issue by piaudonn** [briandelmsft/SentinelAutomationModules#145]
Or another mapping service.
So Bing Maps requires an API key (and so are other services online it seems). So it would need a KeyVault.
Also, the output of the API is a base64 image. It can be used in an email, but it can't be used as-is in an incident comment. It would require a storage account to store the picture of the map in.

**Comment by piaudonn** [comment]
Might be doable with the export feature of render.openstreetmap.org without API keys but with limited options.

**Comment by piaudonn** [comment]
Bing Maps API would be a nice addition...
![image](https://user-images.githubusercontent.com/22434561/145734127-018f1194-0cc0-4d8b-a7fa-6fa8d5ca09b4.png)
Could we just have an optional module maybe? We check if it is there in modules which can use it, if it is there it uses it, if not it fails silently and just doesn't add the nice things.

**Comment by briandelmsft** [comment]
have you looked at Azure Maps? https://docs.microsoft.com/en-us/azure/azure-maps/about-azure-maps#:~:text=%20What%20is%20Azure%20Maps%3F%20%201%20Map,visualizations%20for%20spatial%20data%20on%20top...%20More%20

**Comment by briandelmsft** [comment]
No request so far for this feature

**Comment by piaudonn** [comment]
It seems that the new version of Azure Maps services might be finally having some nice options
https://docs.microsoft.com/en-us/rest/api/maps/render-v2/get-map-static-image
Still not requested, but nice nevertheless :)
