### ISSUE TITLE
AddIncidentComments is not passed to the modules

### ISSUE THREAD

**Issue by piaudonn** [briandelmsft/SentinelAutomationModules#151]
When using the customer connector, the value `AddIncidentComments` is always `null` regarless of the operator's selection in the call.

Example, calling the module with the following parameters:
![image](https://user-images.githubusercontent.com/22434561/145594125-6e8d9d77-dfb2-4184-a504-42b36f0905bc.png)

This is what I get in trigger in the called module:

`    "body": {
        "AddIncidentComments": null,
        "CheckAccountEntityMatches": true,
        "CheckHostEntityMatches": false,
        "CheckIPEntityMatches": false,
        "Entities": "{\"Ac....... TRUNCATED ........\"}",
        "LookbackInDays": 14
    }
}`

**Comment by briandelmsft** [comment]
Fixed in b938385
