### ISSUE TITLE
HighestRiskLevel missing from the AAD Risk module output

### ISSUE THREAD

**Issue by piaudonn** [briandelmsft/SentinelAutomationModules#158]
https://github.com/briandelmsft/SentinelAutomationModules/edit/statconnector/Connector/azuredeploy.json

This (line 1678)
```
"HighestRiskyUser": {
    "type": "string",
    "description": "HighestRiskyUser"
},
```
Should be:
```
"HighestRiskLevel": {
    "type": "string",
    "description": "HighestRiskLevel"
},
```

**Comment by piaudonn** [comment]
I can commit to the connector branch but I don'twant to mess with your flow :)

**Comment by briandelmsft** [comment]
Fixed in referenced commit
