### ISSUE TITLE
Missing Permissions - Handling Failure

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#165]
Doing some testing with some of the modules, i started to test how they behave when the API permissions are not present and at present it's not really consistent.

For example, the base module will successfully return with the RawEntity data only.... we discussed this behavior in the past in the context of an unresolved entity (404 type error), but in the context of a 401/403 error I think it makes more sense to have the module return a failure back to the connector.

Similarly other modules have different behaviours, OOF still works and returns an unknown state, which I think is right again in the case of 404 or other unknown error, but in a 401/403 where it has no chance of succeeding I think we should just return an error.

Other modules just outright fail but return nothing to the connector, so it retires and times out.  Related alerts for example tries the HTTP call to the log analytics API, hits a 403 and then the module stops with no response

My thoughts are if we hit a 401/403 on a critical API call, then we consistently return an error regardless of a possible ability to proceed.  If the API call is less critical then perhaps we can continue...  Something simple like:

```
{
    "Error": "Module does not have sufficient permissions, please run the GrantPermissions.ps1 script"
}
```

**Comment by piaudonn** [comment]
Should we check if permissions are set or handle error management in the code?
Might be easier to add a step like we do to check if the right type of entities are present? Like check permissions and Terminate if that's not there? Or should we do terminate at the actual call? Also, should "Error" me a property we always return even when there is a success? Or maybe add a "Status" property woith either Success, Error or maybe Warning. Although I guess it would be easier to stay binary...

**Comment by briandelmsft** [comment]
I'd lean towards doing it the API call because we could handle additional failure scenarios there.  For example in the KQL module, a ln incorrectly formatted KQL query.

Return schema definitely needs some more thought, we could return an error specific to STAT and the raw error from the API call for additional detail

Interesting idea to add this as a success when no error.

**Comment by piaudonn** [comment]
Perhaps the errors should only be handled by the custom connector either in the connector reading the error code returned by the module or the dispatcher? We can't have the end-user check if there was an error level returned. If anything else than a success is returned by any modules down the line, the connector should be ❌. This can also allow a complex error coding at the internal level, but it should necessarly fail for the end user.

**Comment by briandelmsft** [comment]
I agree but to do that we'll need the modules to pass the 'why' back to the dispatcher so that it is surfaced in the connector.  Otherwise the connector will fail with a useless error like some timeout or similar that isn't as helpful as it could be in diagnosing the issue.  If a critical failure agreed with need a :x: status in the connector

**Comment by briandelmsft** [comment]
Thinking of a return along these lines... I think we should probably come up with more intuitive property names but as a structure it gives us something to start with.  Perhaps we should also include properties for the playbook name and run id to make it easier to locate to troubleshoot.

![image](https://user-images.githubusercontent.com/68655382/146790092-5b875be7-2fc6-46a4-8364-db5dab5035e2.png)

**Comment by briandelmsft** [comment]
Here's a sample of what the would look like with the playbook id, name and run id included

```
{
    "kind": "Http",
    "inputs": {
        "statusCode": "@outputs('HTTP')['statusCode']",
        "body": {
            "Error": "Watchlist module failed to execute with status @{outputs('HTTP')['statusCode']}",
            "PlaybookName": "@{workflow()?['name']}",
            "PlaybookResourceId": "@{workflow()?['id']}",
            "PlaybookRunId": "@{workflow()?['run']?['name']}",
            "SourceError": "@body('HTTP')"
        }
    }
}
```

**Comment by piaudonn** [comment]
Would `"SourceError": "@body('HTTP')['error']"` be a better content for `SourceError` by the way?

**Comment by briandelmsft** [comment]
Yes, looking back at the modules I've tested so far that seems to be consistent and would be better.  Shall we make it ``` "SourceError": "@body('HTTP')?['error']" ``` just be be safe in the event in some corner case error isn't present?

**Comment by briandelmsft** [comment]
Looks like we're done here 😄
