### ISSUE TITLE
Workbook for monitoring and configuration checks

### ISSUE THREAD

**Issue by piaudonn** [briandelmsft/SentinelAutomationModules#179]
Provide a workbook to monitor:

1. Runs by playbooks with Failure/Success rate
2. Count of billable actions for billing visibility
3. General configuration (list of installed playbooks with version number - and if that's the most recent)

The workbook could be deployed automatically (default install mode) or if opt-in in advanced mode. Names of the resources in the workbook code would be parameters taken from the deployement.

**Comment by piaudonn** [comment]
For 3. Maybe having a json available somewhere on the workspace with the latest version available for each component would help as it can be used in a workook (custom endpoint request) to compare what is installed with the lastet version.

**Comment by piaudonn** [comment]
@briandelmsft 

Do you think that would be fine to create a file like StatVersions.json and put it into a .hidden folder.
The content could be something like:

```
{
    "AADRisksModule": {
        "currentVersion" : "0.0.1",
        "currentVersionReleasedDateTime" : "2021-12-26T13:45:00.000Z"
    },
    "BaseModule": {
        "currentVersion" : "0.0.1",
        "currentVersionReleasedDateTime" : "2021-12-26T13:45:00.000Z"
    },
    "FileModule": {
        "currentVersion" : "0.0.1",
        "currentVersionReleasedDateTime" : "2021-12-26T13:45:00.000Z"
    },
    "KQLModule": {
        "currentVersion" : "0.0.1",
        "currentVersionReleasedDateTime" : "2021-12-26T13:45:00.000Z"
    },
    "MDEModule": {
        "currentVersion" : "0.0.1",
        "currentVersionReleasedDateTime" : "2021-12-26T13:45:00.000Z"
    }, ...
}
```
And be updated automatically with some GitHub actions?
This then can be queried from a workbook (and or ALA) to check the latest version and if there is a need for update.

**Comment by briandelmsft** [comment]
I'm not sure how easy it would be to update it with a github action but sounds reasonable to do for sure.

**Comment by briandelmsft** [comment]
also, don't think we really need to put it in a hidden folder, I think just putting it in the root of the Modules folder would be fine

**Comment by piaudonn** [comment]
Here is the json for the workbook: https://github.com/briandelmsft/SentinelAutomationModules/blob/workbook/Workbook/workbook.json
It just checks for module versions for now, not the connector.

**It is not the json of the ARM template but the code of the workbook.**
The fallbackressourceid isn't dynamic then.

@briandelmsft give it a try and tell me if that works for you.

**Comment by briandelmsft** [comment]
Looking pretty cool.. I did have one issue, it defaulted to a subscription that didn't have the workbooks and there was no easy way to change that.  You probably need to add a subscription parameter and have the listlogicapps parameter determine which subscription to look at based on the subscription(s) selected

**Comment by briandelmsft** [comment]
the billable actions graph is a bit hard to really interpret
![image](https://user-images.githubusercontent.com/68655382/148849092-8112af18-87f7-4507-ad48-df4eced296d9.png)

**Comment by piaudonn** [comment]
@briandelmsft can you create the ARM template from the workbook JSON?
I can't do it for some reason it will never import (like the other day, it just hangs there... and I can't restart for now...

**Comment by briandelmsft** [comment]
Sure I'll give it a try
