### ISSUE TITLE
Module internal names

### ISSUE THREAD

**Issue by piaudonn** [briandelmsft/SentinelAutomationModules#181]
Should modules have internal names the same way they have a version number? We could also have some additional properties such as ProjectName or something of the sort. 
This would allow easy identification of all the components of the solution by parsing the ARM information even if the operator who has imported the template gave different names to them. Without having to use tags (as customers might already have specific usages or naming conventions with tags)

For example, if we had a property called ProjectName and another called PlaybookInternalName, then we could list all resources using the Azure Resource Graph:
```
resources
| where type == "microsoft.logic/workflows"
| where properties.definition.parameters.ProjectName.defaultValue == "STAT"
| extend State = properties.state
| extend InternalName = properties.definition.parameters.PlaybookInternalName.defaultValue
| extend Created = properties.createdTime
| extend Modified = properties.changedTime
| extend Version = properties.definition.parameters.PlaybookVersion.defaultValue
| project Name = iif(State == "Enabled", strcat("🟢 ",name),strcat("🔴 ",name)), Version, Created, Modified
```
![image](https://user-images.githubusercontent.com/22434561/147239686-1b6a73f4-c5c7-482b-9a74-0a304a2fb574.png)

The InternalName can then be used to join on a file containing the latest version number per module names.
It can also be used for the error handling to replace the "hardcoded" value such as:
![image](https://user-images.githubusercontent.com/22434561/147240122-62d25db8-57eb-48e4-a8b9-098c14ee1598.png)

**Comment by briandelmsft** [comment]
Sounds good to me 👍
