### ISSUE TITLE
Workbook Version Update Issue

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#213]
The STAT Workbook 'Updated Versions Available' section has 2 I can see:

1. The second merge in this query is 'inner unique' which is causing not all updates to be seen if multiple versions of STAT are installed.  This should be a Full inner join
2. Not sure why on this one yet but the AADRisks and MDE modules seem to be missing even when a version update is needed for those modules.

**Comment by piaudonn** [comment]
Ok, pb identified. That's so ridiculous that I will burn all previously pushed workbook versions 🔥 Will Push later tonight...
