### ISSUE TITLE
Normalize incident comments

### ISSUE THREAD

**Issue by piaudonn** [briandelmsft/SentinelAutomationModules#221]
Ensure that the incident comments' look and feel from all modules are consistent with each other.

**Comment by briandelmsft** [comment]
👍

**Comment by briandelmsft** [comment]
We also need to consider for this to ensure each comment has some logic to maximize its chance for success due to the 3000 character limit... perhaps we need to put a failure branch in to just comment a backup high level summary if the detailed comment fails
