### ISSUE TITLE
[Feature] Add MFA/SSPR User Status to Base Module

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#230]
Add users MFA/SSPR status to base module

**Comment by piaudonn** [comment]
+1 here, as discussed the other day it is described here: https://docs.microsoft.com/en-us/graph/api/resources/credentialuserregistrationdetails?view=graph-rest-beta


isCapable | Boolean | Indicates whether the user is ready to perform self-service password reset or MFA.
-- | -- | --
isEnabled | Boolean | Indicates whether the user enabled to perform self-service password reset.
isMfaRegistered | Boolean | Indicates whether the user is registered for MFA.
isRegistered | Boolean | Indicates whether the user has registered any authentication methods for self-service password reset.

Would require the Base Module to have the `Reports.Read.All` permission and fail safe.
Then the call would be something like:

`GET https://graph.microsoft.com/beta/reports/credentialUserRegistrationDetails?$filter=userPrincipalName eq 'lala@contoso.com'`
