### ISSUE TITLE
[Feature] IP Prevalence

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#250]
Show prevalence of communications with an IP address.  How many unique sources are talking to it?  Cross reference MDE logs and ASIM Network session to locate data?  Maybe SigninLogs to see how many people have signed in from it?  When was the first time the IP was seen?

**Comment by piaudonn** [comment]
perhaps adding a flag public/private IP? Or is that maybe something to do in the base module?
