### ISSUE TITLE
[Feature] Docs Architecture diagram

### ISSUE THREAD

**Issue by ThijsLecomte-TC** [briandelmsft/SentinelAutomationModules#256]
I was confused at first on how this works (having the Logic Apps incorporated in a connector). Having a small diagram with the different parts (and also the integration of additional samples) would go a long way.

**Comment by briandelmsft** [comment]
Thanks for your feedback on this, please let me know if the proposed changes cover what you were thinking about.

**Comment by ThijsLecomte-TC** [comment]
That's great @briandelmsft
