### ISSUE TITLE
[Feature] Authentication between Logic Apps

### ISSUE THREAD

**Issue by ThijsLecomte-TC** [briandelmsft/SentinelAutomationModules#257]
Could we look into authentication between the different Logic Apps and modules?
It's currently just HTTP requests which is protected by a signature.

Would be great to look into AAD Authentication using the Managed Identities

**Comment by briandelmsft** [comment]
Thanks for the feedback, it is an interesting idea.  Converting the logic apps to use a token from a managed id to authenticate is certainly possible.  However it will add some significant complexities as if the authorization policies are not done correctly we could end up in a worst place then with a SAS (ie. anyone with a token from the AAD tenant could be permitted).  Doing the authorization policies correctly would be where part of the complexities would come in and I don't believe there's an option to do this through RBAC.

What if we were to provide an option to automatically (on a configurable schedule) rotate the logic app keys (therefore invalidating the old signatures)?  Would that be sufficient?

**Comment by ThijsLecomte-TC** [comment]
Hi Brian

That would also be an added value. I just prefer to not use the signatures.

If it's all done through the ARM template, it should be good to go. But I agree, this is a feature to implement at a later stage

**Comment by briandelmsft** [comment]
We are planning to move the backend to functions so there will no longer be logic app to logic app communications
