### ISSUE TITLE
[BUG] MCAS Module - API Path Inconsistent with Docs

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#296]
In the MCAS Module, we attempt to use the API path /cas/api/v1/entities/&lt;pk&gt;/ but the [docs](https://docs.microsoft.com/en-us/defender-cloud-apps/api-entities-fetch) indicate it should be /api/v1/entities/&lt;pk&gt;/

this change appeared in 8ea043c4d77065f78accc2fea6b8295ca03b4343 as the /cas/ wasn't originally included but I'm not sure why the change was made, or how it even worked as I verify it was working at the time but the module consistently fails for me until I change the path to as it is in the documentation.

I can easily fix this, but just wanted to check with you @piaudonn if you knew why this is there and if there is an issue changing it

**Comment by piaudonn** [comment]
It's a path I was given in response of thread. I am really not happy with the API call in general since it has to be hardcoded to work (and not even consistently I figured...) I am ok with fixing it the module. You can go ahead if that's not already done.

**Comment by briandelmsft** [comment]
interesting, ok.  I'd like to do a bit more testing with the paths.... one time the path in there didn't work for me at all, even with the correct host set in the variable, but then later it worked so maybe it was a temporary issue
