### ISSUE TITLE
Base Module doesn't show if login from IP address was successful/failed or the resource that was logged into

### ISSUE THREAD

**Issue by over2under3** [briandelmsft/SentinelAutomationModules#298]
**Is your feature request related to a problem? Please describe.**
Currently the STAT base module shows the IP Address and the country/state but it doesn't show if the user logged in successfully or not. Also, I don't see what application the user trued to access

**Describe the solution you'd like**
Regarding the IP address, it would be great to see if a user was able to successfully log from an IP address and also if what application they accessed.

**Describe alternatives you've considered**

**Additional context**

**Comment by briandelmsft** [comment]
The base module really is meant to enrich and normalize the data for other modules, we don't really want to make a lot of assumptions to look up a lot of additional things there as the presence of an IP isn't even necessarily an indication of a logon.  The incident could be about any number of things that are not login related (probing, outbound internet access, etc)  We are planning to introduce a new module to provide AAD Signin Insights (#210) like what you describe.

In the interim, you can do this with the KQL module today.  Here's a simplified example of how to use that module to get success/failure counts from the user/ip in the incident:

```
let UPNs = accountEntities | project UserPrincipalName;
let IPs = ipEntities | project IPAddress;
SigninLogs
| where UserPrincipalName in~ (UPNs)
| where IPAddress in (IPs)
| summarize SuccessCount=countif(ResultType == 0), FailureCount=countif(ResultType != 0) by UserPrincipalName
```

See [this](https://github.com/briandelmsft/SentinelAutomationModules/tree/main/Modules/KQLModule) for more info on how to use the KQL module.

**Comment by over2under3** [comment]
I'm trying to find exactly where you drop this query. I assume it goes under the "Compose Sentinel Query" section Logic Design for this Playbook Logic, correct?

**Comment by briandelmsft** [comment]
You shouldn't ever have to modify the STAT modules themselves, the query will go in your own playbook when you use the KQL Module

Overview of the Playbook:
![image](https://user-images.githubusercontent.com/68655382/176680972-e38a9e22-698d-42fe-9060-53fa46ef219d.png)

The KQL Step configuration:
![image](https://user-images.githubusercontent.com/68655382/176681145-cc7a2711-35fa-4bb3-b4b8-08bd97147d4c.png)

**Comment by briandelmsft** [comment]
I believe this is addressed with the query, if not please feel free to add additional information
