### ISSUE TITLE
[Feature] Enhancement to MITRE Tactics for Related Alerts

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#309]
For #308 we want to add a multiplier to the score based on how many MITRE tactics are related.  While we can do this in the Scoring module itself, it may benefit other use cases to provide a high level summary of MITRE tactics in the raw output of the Related Alerts Module.

Proposing the addition of the following columns in the output, names to be finalized later:

|Name|Description|
|---|---|
|AllTactics|All observed MITRE tactics, including those found in the related alerts, as well as the source incident|
|AllTacticsCount|Count of unique MITRE tactics found in AllTactics|

**Comment by piaudonn** [comment]
I think that one is pretty cool actually.
