### ISSUE TITLE
[Feature] Auto-update

### ISSUE THREAD

**Issue by piaudonn** [briandelmsft/SentinelAutomationModules#315]
Study the possibility of having an auto-update mode.

To enable or disable at installation time and/or at the discretion of the admin. Maybe with options such as all updates, or only major updates etc...

It could be implemented through a logic app that redeploy the solution.

**Comment by piaudonn** [comment]
@briandelmsft would the function be essentially an auto auto-update with the option "run from web"?

**Comment by briandelmsft** [comment]
@piaudonn right now we're pointing to an explicit build so it wouldn't auto-update unless we changed the build, but we could have an option to publish the most recent build to a common location and during the setup give a user the choice of auto-update or not 

If they choose auto update we would point to something like /main/builds/stat.zip
If they choose manual we would point them to /releases/download/v2.x.x/stat.zip

**Comment by briandelmsft** [comment]
The connector wouldn't auto update either way

**Comment by piaudonn** [comment]
I think that

**Comment by piaudonn** [comment]
Judged to risky.
