### ISSUE TITLE
[Feature] Add Data Processing Azure Function

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#324]
Logic apps have some limitations that limit data processing functionality.  For example, sorting an array of JSON objects by a property of the JSON object.  Also, dealing with complex API output like that of the Log Analytics API require Logic apps to go through many iterations of a loop which makes dealing with large datasets difficult and slower.

Add an Azure Function which can be called behind the scenes by STAT modules to aide in these data processing functions

**Comment by briandelmsft** [comment]
Development work will be in the function_dev branch

[Deploy Dev Branch](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fbriandelmsft%2FSentinelAutomationModules%2Ffunction_dev_deploy%2FDeploy%2Fazuredeploy.json/createUIDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fbriandelmsft%2FSentinelAutomationModules%2Ffunction_dev_deploy%2FDeploy%2FcreateUiDefinition.json)

**Comment by piaudonn** [comment]
I Am So Excited About This One :)

**Comment by piaudonn** [comment]
If we customize the function name, the deployment might fail if the provided name is using a forbidden character for the storage account or a name too long once we concatenate the name and the random string. Would that deserve a check or a string operation in the name generation?

**Comment by briandelmsft** [comment]
> If we customize the function name, the deployment might fail if the provided name is using a forbidden character for the storage account or a name too long once we concatenate the name and the random string. Would that deserve a check or a string operation in the name generation?

Yeah, right now there's a lowercase function on it but that is all.  We can do regex validation on the text box input.

https://learn.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/microsoft-common-textbox

**Comment by briandelmsft** [comment]
Validation has been added so that you can't pass an invalid name/length for the function name

![image](https://user-images.githubusercontent.com/68655382/197046246-536173e3-8780-42f4-af6a-4d6632aad769.png)

I also added validations to ensure permissions to create logic apps, Azure Functions, App Service Plans and Storage accounts are in place

![image](https://user-images.githubusercontent.com/68655382/197046020-c1a560bb-ce49-4808-879d-6441dad2dc05.png)

**Comment by briandelmsft** [comment]
@piaudonn 

I've got the function now working in PowerShell which should give greater region support.  I'm having a challenge with the deployment though.  The function consistently deploys without error and seems to work fine, but 1-2 of 3 modules (Base, Scoring and KQL) are now inconsistently failing to deploy.  Consistently at least 1 fails, usually 2.  Now those modules are the only ones that reference the function, but they are all dependent on the function deployment in the template so it shouldn't be an issue.  The stranger part, if you run the deployment a second time it all works fine.

[Deploy PS Function](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fbriandelmsft%2FSentinelAutomationModules%2Ffunction_dev_ps%2FDeploy%2Fazuredeploy.json/createUIDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fbriandelmsft%2FSentinelAutomationModules%2Ffunction_dev_ps%2FDeploy%2FcreateUiDefinition.json)

**Comment by piaudonn** [comment]
@briandelmsft I think this one can be closed as the data processing is inherently a part of statv2 function.
