### ISSUE TITLE
[Feature] Base Module - Parse Custom Details

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#328]
In an analytics rule custom key value pairs may be added to the alert:

![image](https://user-images.githubusercontent.com/68655382/200630307-89d52c44-90b9-4f33-8bfe-355a27f764d3.png)

Add parsing for them and include them in the Base Module output

**Comment by piaudonn** [comment]
I suppose the idea is to surface them in the data model of the Base module?

**Comment by briandelmsft** [comment]
Yes, it's a nice to have.  Not a major feature... One challenge is the data passed to the base module doesn't include it so it's not as simple as just parsing it.  We'd either need to add an input to the base, or have the base module call the incident API to get it.  Also, this is stored at the alert level so there could be multiple alerts that carry different custom properties

**Comment by piaudonn** [comment]
Maybe we should check what's the road map about adding the custom entities/properties to the default model passed to automation. That would make the integration super simple.

**Comment by briandelmsft** [comment]
@piaudonn I did a bit of research into this and it is passed in the incident trigger however, we are not passing that data along to the base module.

The structure of it is difficult for the average person building an automation to extract, so there could be benefit for us doing the heavy lifting.

Here's an extract of the relevant part from the incident trigger payload

```
                "alerts": [
                    {
                        //truncated..
                            "additionalData": {
                                //truncated..
                                "Custom Details": "{\r\n  \"RecordId\": [\r\n    \"c46173e6-dd8a-469d-a6d3-60731749a7b1\"\r\n  ],\r\n  \"Temp\": [\r\n    \"abc\"\r\n  ]\r\n}"
                            },
                            "friendlyName": "Custom Properties Test"
                        }
                    }
                ]
```

As you can see it's buried in the alerts array, as this data could be different from alert to alert, and within that array, it's stored as an escaped json in a string, with each of the values being their own array 😢 

Given the amount of effort here (needing to add an input to the base module + the actual processing) vs the need for this data I think we close this one for now and we can come back to it if further use cases show that this is important to have.  Thoughts?

**Comment by briandelmsft** [comment]
Due to the complexity of the structure, and we don't know the fields that will be here there's limited benefit we can provide with this feature.  We can't add parsing to the custom connector for example, as we don't know in advance what fields are going to be available
