### ISSUE TITLE
What permissions does the deploying account need for the PS1 grant permissions script?

### ISSUE THREAD

**Issue by noapocalypse** [briandelmsft/SentinelAutomationModules#329]
HI,

I get multiple of the following errors when running the grant perms script.

Just wondering if you could suggest what perms i might be missing? Or could provide a list of required perms for executing the ps1 file 

Cheers!

New-AzureAdServiceAppRoleAssignment : Error occurred while executing NewServicePrincipalAppRoleAssignment
Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.
RequestId: b066e691-bc6a-4f68-b381-df97a79a78f6
DateTimeStamp: Fri, 11 Nov 2022 13:29:27 GMT
HttpStatusCode: Forbidden
HttpStatusDescription: Forbidden
HttpResponseStatus: Completed
At C:\Users\GrantPermissions.ps1:33 char:5
+     New-AzureAdServiceAppRoleAssignment -ObjectId $MSI.ObjectId -Prin ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureADServiceAppRoleAssignment], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.NewServicePrincipalAppRoleAssignment

**Comment by briandelmsft** [comment]
Hi @noapocalypse 

The script has 2 different functions which call into other PowerShell commands.  These functions have different permissions requirements for the commands to complete successfully.  You can break it up if you need to run these under different accounts.

|Function|Permissions|
|---|---|
|Set-APIPermissions|The calls to this function require the user to be either a Azure AD Global Administrator or an Azure AD or an Azure AD Privileged Role Administrator|
|Set-RBACPermissions|The calls to this function require the user to be either a Resource Group Owner or User Access Administrator on the Resource Group where Microsoft Sentinel is installed|

The New-AzureAdServiceAppRoleAssignment cmdlet is part of the Set-APIPermissions function so it looks like the account was lacking either Azure AD Global Admin or Privileged Role Administrator.

I will use this issue to track updating the docs
