### ISSUE TITLE
[Feature] Documentation update request

### ISSUE THREAD

**Issue by mgijo** [briandelmsft/SentinelAutomationModules#334]
**Is your feature request related to a problem? Please describe.**
The documentation for this project is great. I would request you to add one more detail with regards to the documentation steps so it would be easy for others who are not much familiar with Azure Logic Apps

**Describe the solution you'd like**
If a user wants to add additional STAT modules to their existing workflow - we have to choose "Custom" and then select the additional modules. Not many are familiar with this, and I also had to take sometime to find where this was located. I believe adding it into the documentation steps would help.

![image](https://user-images.githubusercontent.com/83291280/203377161-7ef6dcdf-fec2-435a-9e31-8c876d23babb.png)

**Comment by briandelmsft** [comment]
Thanks for the feedback @mgijo 

We will get something added to the docs to reflect this soon.
