### ISSUE TITLE
Sentinel Tasks Integration

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#348]
@piaudonn (and anyone else who has input)

With the introduction of [Incident Tasks](https://learn.microsoft.com/azure/sentinel/work-with-tasks) in Microsoft Sentinel I think it presents us with an opportunity to enhance some of STAT's incident enrichment capabilities which currently leverage comments.

Tasks provide a few advantages over comments that could be useful, for example, with a task it has a completed/incomplete status.  Also, the tasks status is highlighted in the incident pane making it very visible that there are incomplete tasks associated with the incident.  With comments, we don't really know if anything was done with the information in a comment, and they could be more easily overlooked if an analyst is not expecting the incident to come with comments.

With that in mind I think some integration with tasks would be useful, but what should it look like?

Do we take a first step of just converting all comments to tasks and reframe them as Review the related alerts...?
Should (and if so how) do we enhancement the enrichments around tasks? for example
- AAD Risks could pivot into a link to identity protection with the instructions to review
- UEBA could link to the users timeline page
- MDE could link to the device page
- File could link to the file telemetry page

If we do this, do we provide an option to add tasks into the existing modules?  Do we make adding a task the default? Do we remove the comment option?

We may need to do away with, or reformat some of the tables that go into comments to put them into tasks as we could run into formatting issues as the tasks pane is rather narrow.

**Comment by briandelmsft** [comment]
So right now we have a AddCommentsToIncident true/false (default:true) on all the modules, let's say we add an AddTasksToIncident true/false (defualt:false)

If AddCommentsToIncident=true and AddTasksToIncident=false ➡️ it will work the same as it does today
If AddCommentsToIncident=true and AddTasksToIncident=true ➡️ If there's a finding, we add a task to follow up on the finding (like a risky user), if there is no finding, we add a comment to indicate that the module ran, but there was nothing found
If AddCommentsToIncident=false and AddTasksToIncident=true ➡️ We add tasks if there's findings, but nothing if there isn't
If AddCommentsToIncident=false and AddTasksToIncident=false ➡️ We add no enrichment, regardless of if we found anything

Or do we consider implementing this somewhere else, like in the scoring module and only assign tasks if there's a associated risk score?

**Comment by piaudonn** [comment]
I think the logic of whether there is a finding to put in the task should live in the module. It would make it less flexible, but easier to manage. Besides, nothing prevents users from adding ad-hoc task after running the Scoring module. Maybe that could be one of the examples we document/demo.

**Comment by briandelmsft** [comment]
@piaudonn that makes sense to me... does the Logic in my above comment make sense to you about introducing an AddTasksToIncident toggle and how that would default/be used in conjunction with the AddCommentsToIncident toggle?

**Comment by briandelmsft** [comment]
Task descriptions are limited to 3000 characters, some we won't be able to take some module outputs as is.... commonly related alerts and KQL module outputs will exceed this.

**Comment by briandelmsft** [comment]
Created per work item issues
