### ISSUE TITLE
Run On Demand on Incident

### ISSUE THREAD

**Issue by zrahim-cybermsi** [briandelmsft/SentinelAutomationModules#352]
Can we deploy the standalone the BaseModule and run on Incident on demand?

**Comment by briandelmsft** [comment]
Hi @zrahim-cybermsi 

Yes, it can be done.  The ARM template for just the base module can be found [here](/briandelmsft/SentinelAutomationModules/blob/main/Modules/BaseModule/azuredeploy.json)

To call it, create another Logic App with a Sentinel Incident trigger and add a 'Logic apps' step to call the Base-Module
![image](https://user-images.githubusercontent.com/68655382/212361826-be4265c9-250c-48d4-8ee3-40b28e6375f4.png)

If you want to parse the output to use in your own ways, the JSON schema is [here](/briandelmsft/SentinelAutomationModules/blob/main/Modules/BaseModule/returnschema.json) and can be put into a Parse JSON with the body of the Base-Module response.

You will still need to [grant permissions](/briandelmsft/SentinelAutomationModules/blob/main/Deploy/) to the base module.  You can extract the base module specific permissions from the scripts in the deployment section of the repo.

**Comment by piaudonn** [comment]
@zrahim-cybermsi, I see you have written an article about this :) Feel free to share the link here! In the meantime, I'll close this issue.
