### ISSUE TITLE
[Feature] Multi Tenancy support (f.x. for MSSP's)

### ISSUE THREAD

**Issue by olibbb** [briandelmsft/SentinelAutomationModules#360]
Could we explore the possibility of making STAT support multi tenant scenarios f.x. for MSSP's? 
F.x. my company is an MSSP and we have all our playbooks hosted on our tenant and is treated as our IP. 

We would like to deploy STAT over our whole customer base, but then we would need to make the graph API calls via a multi tenant app as managed identities cannot be given Graph API permissions cross-tenant. 

The azure permissions should work without changes when the appropriate lighthouse permissions are given to the managed identities.

We are currently using table storage to keep info about our customer environments f.x. Sentinel name, resource group name, tenant id etc. which we utilize to match an incident to the correct customer. We could f.x create a playbook to handle getting graph tokens via a multi-tenant app. 

We would like to make this as future proof as possible in regards to updates to the STAT module and f.x. we make changes to authentication and then updates to the STAT module breaks those changes. 

Would like to get your guys thoughts on this :)

**Comment by briandelmsft** [comment]
Hi @olibbb , thanks for bringing this up.  We are definitely interested in exploring the options to make this more multi-tenant friendly.

My initial thoughts on this would actually be to separate the STAT Custom Connector, from the rest of the STAT modules.  Such that the STAT modules still get deployed into the customer tenant, but the STAT connector (or maybe a special MSSP version of it) gets deployed into yours.  

While the current deployment doesn't support this, there's no technical limitation to split this.  This way all the modules would still use managed identities in the customer tenant, but you IP of how you use STAT modules and the decision making around it would all be protected in your tenant.  The customer would get some insight into what modules were called, what KQL queries were sent (but they could get that through KQL logging anyways), but not really have any insight into how you handle that data.  If you plan to use the scoring module, that too could be separated to run in your tenant as the only thing it uses a managed identity for is commenting to the incident which could either be turned off, or still executed through lighthouse.

I'm sure there could be some unforeseen challenges doing this, but barring anything major I think this would be a relatively simple modification to open up this kind of MSSP use case

Thoughts?

**Comment by hitem** [comment]
I would chip in that this would be great! Specially with lighthouse integration - im going to do some tests to deploy it all in my tenant (and sentinel) and then give those manage identities a group membership that is part of the lighthouse integration. 
I have not tested this module before so im sure there is some obv pitfalls here and i dont have multiple test tenants to test against - but hey! If this could work it would be great (the flip side: the logic app trigger cost is on our end instead of customers :D).

**Comment by briandelmsft** [comment]
@hitem please let us know how it goes.  I think the creation of a MSSP connector that is separate from the Modules would be the most balanced option as it would the overall architecture would be similar and the costs would largely stay in the customer tenant, but the key IP on how the automation is used would stay in the MSSP tenant.  I unfortunately don't have the lighthouse/multitenant setup deployed at this time to try this out

**Comment by a-kefallonitis** [comment]
Looking for the same. Alternative would be an multitenant app registration with the required permissions needed for STAT to run Client tenants can accept and delegate and then modify the playbooks to run with app client id / secret

**Comment by briandelmsft** [comment]
We will be migrating the backend logic apps of STAT to a Azure Function.  The front end will remain a custom connector (though there will be a new version with some enhancements).  This will unlock a lot of new possibilities for us, including the ability to support multiple authentication options including service principal, system managed identity and user assigned managed identity.  This is quite a bit of effort to make this move but it will be worth it.

Would appreciate your feedback on the minimum set of modules you would need to have a minimum viable product.  The base module goes without saying, but if you could have only 3 or 4 modules, for an initial test release, what would they be?

**Comment by a-kefallonitis** [comment]
I think for an MSSP version an app registration authentication works like a charm as by creating a multi tenant app a customer tenant can invite the service principal in to their tenant and delegate the permissions needed for the stat to run. Not sure with Azure function we can use this method.

**Comment by briandelmsft** [comment]
@olibbb @hitem @a-kefallonitis 

We've made some significant progress on MSSP support, hoping to have something for you all to start testing by the end of the month.  One particular point we would like a bit of feedback on is how we plan to pass the tenant information needed to obtain the correct token with a multi-tenant service principal.  

STAT currently uses 5 different APIs (ARM, MSGraph, Log Analytics, M365D and MDE) and in an MSSP scenario some of those APIs may need to be accessed in different tenants when working with the same incident.  For example, if the Incident exists in the MSSP tenant, but the automation needs to call the MSGraph in the customer tenant.

In @olibbb original post it is indicated that
> We are currently using table storage to keep info about our customer environments f.x. Sentinel name, resource group name, tenant id etc. which we utilize to match an incident to the correct customer. We could f.x create a playbook to handle getting graph tokens via a multi-tenant app.

What we are planning, is that when you call the base module you pass an additional parameter with the tenant id information necessary to that incident and then STAT will do the rest.  So imagine the base module has an optional field you can populate called MultiTenantAuthConfig and you populate it with something like this:

```JSON
{
    "MSGraphTenantId": "<IdOfTenantForMSGraphQueries>",
    "ARMTenantId": "<IdOfTenantForARMAPI>",
    "MDETenantId": "<IdOfTenantForMDEAPI>",
    "M365DTenantId": "<IdOfTenantForM365DAPI>",
    "LogAnalyticsTenantId": "IdOfTenantForLogAnalyticsWorkspace"
}
```
So, if in your config the incident is in the MSSP tenant, but all the other APIs are in the customer tenant you would dynamically pass the appropriate tenant IDs based on that configuration, the base module would use that and pass that to other modules for their consumption.

If this parameter is not passed to the base module, we would assume that all resources are in the same tenant as the service principal.

Thoughts?  Do you see any issues with this?

**Comment by olibbb** [comment]
@briandelmsft 

In my case and I presume in most MSSP's utilizing Sentinel the incidents are contained in the customers tenant. I don't think it would be necessary to have to specify the tenant. 

Microsoft architecture guidelines regarding MSSP's recommend Azure lighthouse for delegated permissions to the customer environment and I can't really imagine that MSSP's are using a central Sentinel instance.

I guess it wouldn't hurt though to have the tenantID parametrized as you say but have the default tenantID be the customers tenant.

Regards
Óli Björn

**Comment by a-kefallonitis** [comment]
@briandelmsft what you said is the exact thing i had in mind to be able to run it through the MSSP tenant completely

@olibbb we need graph api calls in order for stat to run thus the need to pass tenantid parameter

**Comment by briandelmsft** [comment]
@olibbb @hitem @a-kefallonitis 

STAT v2 Preview is ready for you to try.  This is a major move forward from previous versions of STAT, now using an Azure Functions backend and Logic Apps front end.  The look and feel is the same as v1, but the improvements on the backend are substantial. This is also a complete rewrite of all of the backend functionality, so do be aware there may be some undiscovered bugs, though there are no known issues in this build.  If you encounter any bugs, or even unexpected changes in functionality from previous version please open an issue no matter how small the issue may be.

This build includes the following new features:

- Backend of STAT is now using Azure Functions instead of Logic apps
- Support for User Assigned Managed Identities, Service Principal and Multi Tenant service principal authentication (in addition to existing system assigned managed id support)
- Support for the Sentinel Alert trigger (in addition to existing incident trigger)
- Ability to create a new Sentinel incident from an alert and automatically link the alert
- Additional performance and other minor improvements

The Preview [deployment](https://github.com/briandelmsft/SentinelAutomationModules/tree/statv2_preview/Deploy) can be found only in the statv2_preview branch of this repo as well as supporting [documentation](https://github.com/briandelmsft/SentinelAutomationModules/blob/statv2_preview/Docs/). That includes documentation specific to [multi-tenant/MSSP](https://github.com/briandelmsft/SentinelAutomationModules/blob/statv2_preview/Docs/mssp.md) scenarios.

The main branch does not contain any information about v2 at this time, so ensure you select the correct branch.

**Comment by briandelmsft** [comment]
@olibbb @hitem @a-kefallonitis has anyone be able to give this a try yet?  Any issues or feedback?

**Comment by olibbb** [comment]
I’m on vacation at the moment. Very excited to try it when I get back. On 20 Jul 2023, at 01:02, Brian Delaney ***@***.***> wrote:﻿
@olibbb @hitem @a-kefallonitis has anyone be able to give this a try yet?  Any issues or feedback?

**Comment by nbutl008** [comment]
> @olibbb @hitem @a-kefallonitis has anyone be able to give this a try yet? Any issues or feedback?
![Screenshot 2023-07-21 123720](https://github.com/briandelmsft/SentinelAutomationModules/assets/126900043/c7009db1-9bce-4c80-861a-9d01f56cf93d)
We are following the prereqs and need to understand what it means to "Run the GrantPermissions.ps1 against this service principal"  

We just need high-level steps of what needs to be done.

**Comment by briandelmsft** [comment]
@nbutl008 

1. Download the [GrantPermissions.ps1](https://github.com/briandelmsft/SentinelAutomationModules/blob/statv2_preview/Deploy/GrantPermissions.ps1)
2. Near the top of the script update the PowerShell variables with the relevant information

```
$TenantId = "" #Azure AD Tenant Id of your Tenant where the Multi tenant SP lives 
$AzureSubscriptionId = "" #Subscription Id where your Sentinel Instance lives (if you have one)
$SentinelResourceGroupName = "" #Resrouce group name where you Sentinel Instance lives (if you have one)

$STATIdentityName = "" #Name of the Multi Tenant Service Principal
```
> If you do not have a Sentinel instance and only your customers do, the RBAC part of the script will fail but that is ok

To grant consent in the customer tenant you will need to get the customer tenant domain and the client id of your multi tenant SP and add them into this URL:

https://login.microsoftonline.com/customertenant.onmicrosoft.com/adminconsent?client_id=<clientidsp>

Using a customer Global admin go the URL and consent to the access.  Then grant Sentinel Responder access to that managed id to the RG where Sentinel is in the customer tenant

**Comment by olibbb** [comment]
@briandelmsft 

Finally got back from vacation. I've set up the v2 preview with the multi-tenant service principal without issue. 

Only one quirk was after running grantpermissions.ps1 I had to approve the non graph API permissions by adding them to the requested API permissions in the app registration. But that was not a big deal.

Currently only have it running on one customer. Is there anything you would like me to test specifically?

**Comment by briandelmsft** [comment]
Hi @olibbb 

> Only one quirk was after running grantpermissions.ps1 I had to approve the non graph API permissions by adding them to the requested API permissions in the app registration. But that was not a big deal.

Can you detail those steps so that we can document them?

> Is there anything you would like me to test specifically?

Nothing specific really, we haven't seen any big issues so far with v2, and the issues we have since have been fixed already, but have also had very limited testing with cross-tenant so even if you're not going to use all the modules, trying as many of them as possible would be greatly appreciated

**Comment by SimonRefslund** [comment]
@briandelmsft 

I have a question regarding the MultiTenantConfig when deploying to multiple customers.
Lets say i want to deploy this to 3 tenants. All incident data are kept in the customer tenant, with STATv2 deployed in MSSP tenant.

Would the MultiTenantConfig JSON look something like this?

```
{
  "Tenants": [
    {
      "TenantId": "customer1-tenant-id",
      "MDCAUrl": "https://custumer1.region.portal.cloudappsecurity.com"
    },
    {
      "TenantId": "customer2-tenant-id",
      "MDCAUrl": "customer2.region.portal.cloudappsecurity.com"
    },
    {
      "TenantId": "customer3-tenant-id",
      "MDCAUrl": "customer3.region.portal.cloudappsecurity.com"
    }
  ]
}

```

**Comment by SimonRefslund** [comment]
I see. That makes sense.

Thank you!
