### ISSUE TITLE
[BUG] Get-MDEInsights - Fails with 414 when user associated with many devices

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#389]
In the Account scope, when many devices are returned for a single a user in the ```MDE - Get Devices by SID``` step the, the following ```MDE - Get Machines by Id``` may fail with a 414 - RequestUriTooLong.

The device filter in this step is passed as part of the query string, and most systems allow 2000 characters to be passed in total. The base URI is about 128 characters + 42 characters per device id.  So, you should be able to pass about 44 devices at a time assuming 2000 characters is in fact the limit.

First we need to check if the API supports passing the filter in the body, as that would be the cleanest solution.  If not, to deal with this we can chunk() the list of machines down to a smaller, safe number and then loop through the chunks.  In most cases there will only be 1 anyways.

Reported in #388

**Comment by briandelmsft** [comment]
API does not support passing the filter in the body, will use chunk() to break down the device list

**Comment by piaudonn** [comment]
Does the API support a base64 input? might be a way to shrink it down.

**Comment by briandelmsft** [comment]
> Does the API support a base64 input? might be a way to shrink it down.

It doesn't appear to, nothing in the docs other than the generic OData support but it doesn't seem to work with the POST /$query approach either

**Comment by piaudonn** [comment]
V2 is chucking the list in packs of 30 devices. 
#419 for reference

**Comment by briandelmsft** [comment]
As Pierre indicated v2 includes chunking to fix this issue when many devices are included in the scope.  That v2 build is now available to try.  More information below.

STAT v2 Preview is ready for you to try.  This is a major move forward from previous versions of STAT, now using an Azure Functions backend and Logic Apps front end.  The look and feel is the same as v1, but the improvements on the backend are substantial. This is also a complete rewrite of all of the backend functionality, so do be aware there may be some undiscovered bugs, though there are no known issues in this build.  If you encounter any bugs, or even unexpected changes in functionality from previous version please open an issue no matter how small the issue may be.

This build includes the following new features:

- Backend of STAT is now using Azure Functions instead of Logic apps
- Support for User Assigned Managed Identities, Service Principal and Multi Tenant service principal authentication (in addition to existing system assigned managed id support)
- Support for the Sentinel Alert trigger (in addition to existing incident trigger)
- Ability to create a new Sentinel incident from an alert and automatically link the alert
- Additional performance and other minor improvements

The Preview [deployment](https://github.com/briandelmsft/SentinelAutomationModules/tree/statv2_preview/Deploy) can be found only in the statv2_preview branch of this repo as well as supporting [documentation](https://github.com/briandelmsft/SentinelAutomationModules/blob/statv2_preview/Docs/). That includes documentation specific to [multi-tenant/MSSP](https://github.com/briandelmsft/SentinelAutomationModules/blob/statv2_preview/Docs/mssp.md) scenarios.

The main branch does not contain any information about v2 at this time, so ensure you select the correct branch.
