### ISSUE TITLE
[QUESTION] Insufficient privileges to complete the operation to call Get-MgServicePrincipal

### ISSUE THREAD

**Issue by shelar1** [briandelmsft/SentinelAutomationModules#406]
While using the base module after getting Sentinel Incidents, I am getting an error of insufficient privileges to complete the operation to call Get-MgServicePrincipal. I was wondering if you could help figure out what is going wrong.

**Comment by piaudonn** [comment]
Hello, you mean you have error running the PowerShell script?
Can you share the output or a screenshot of the error message?

**Comment by piaudonn** [comment]
Unresponsive. @shelar1 please let us to if we need to re-open. Thanks!
