### ISSUE TITLE
[BUG] File Insights - Module fails when file entities are passed but no file hashes

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#412]
If File entities are passed to the module but no file hashes the module fails.  This is due to a max / min function in a compose that tries to look for the max/min in an empty array.

**Comment by piaudonn** [comment]
createarray(0) isn't an empty array?

**Comment by briandelmsft** [comment]
Well have to go back to empty and put a condition on the file hashes branch to set it to 0 if there's nothing in it after the for each loop
