### ISSUE TITLE
[BUG] Issues when deploying Grant Permissions script

### ISSUE THREAD

**Issue by mgijo** [briandelmsft/SentinelAutomationModules#416]
While executing the powershell script to grant permissions - I get the below error:-

![image](https://github.com/briandelmsft/SentinelAutomationModules/assets/83291280/8ba4c469-1ad7-4a36-9272-5177aaa907db)

I am a Global admin and Subscription Owner - not sure why it starts failing at Get-MDEInsights role assignment.

**Comment by briandelmsft** [comment]
hi @mgijo was the script successful in setting the other permissions that are shown as 'Role already assigned' and 'Permission being assigned already exists on the object' during a prior run of the script? or did you grant those permissions in some other way?

Are you operating in the standard M365 / Azure Commercial environment or are you in GCC (Medium? / High?)

Can you try the [legacy](https://github.com/briandelmsft/SentinelAutomationModules/blob/main/Deploy/LegacyGrantPermissions.ps1) script?  It uses a deprecated PowerShell module, but ultimately grants the same permissions.

**Comment by mgijo** [comment]
Hi @briandelmsft  - I ran the script twice and hence the notification "Role already assigned" is displayed. Both times got the same error when executing the script. I ran it on an Azure Commercial environment.

Sure, I will try using the legacy script and update this thread.

**Comment by piaudonn** [comment]
@mgijo any updates?

**Comment by mgijo** [comment]
> 

I have yet to test it out. Will update soon.

**Comment by mgijo** [comment]
@piaudonn - the old [legacy](https://github.com/briandelmsft/SentinelAutomationModules/blob/main/Deploy/LegacyGrantPermissions.ps1) script worked. No issues found.

**Comment by piaudonn** [comment]
Thanks for letting us know!
