### ISSUE TITLE
STAT Support in DoD 

### ISSUE THREAD

**Issue by brandonconn03** [briandelmsft/SentinelAutomationModules#417]
**Is your feature request related to a problem? Please describe.**
I've tried to incoporate into an existing IL4/5 (DoD) environment and having issues with API's. I've been able to solution a significant amount of issues but the 'RelatedAlerts' module continues to give me issues with HTTP requests. 

**Describe the solution you'd like**
I would like to request a proper ARM template deployment for STAT in DoD.

**Describe alternatives you've considered**
 I've been able to solution a significant amount of API with updating approved API versions (management.azure.com, https://api.loganalytics.io, and https://graph.microsoft.com/v1.0) but some issues /errors (404) I cannot troubleshoot. 
 
**Additional context**
![RelatedAlerts-ScopeAPI](https://github.com/briandelmsft/SentinelAutomationModules/assets/18543006/2e5cf126-5942-4da4-9fdc-4971edf71a55)
This always returns a subscriptions not found 404 error but the subscription ID is 100% correct from the Parse JSON results.

**Comment by briandelmsft** [comment]
@brandonconn03 when you ran into this error had you changed the endpoint in the screenshot to management.usgovcloudapi.net or was it using management.azure.com?  Can you provide the details from the error in the failed run of the logic app (please feel free to redact any identifying details of course)?

We have only tested STAT to date in Commercial Azure paired with Commercial Office 365 and Commercial Azure paired with GCC Medium Office 365.  In your case you are using Azure Gov in one of the DoD regions and Office 365 in GCC DoD?

**Comment by brandonconn03** [comment]
@briandelmsft I apologize for my delayed response as I have been TDY. 

I was using management.azure.com and not management.usgovcloudapi.net. I can test with the usgovcloudapi URL to see if that changes anything.

Yes, I am using Azure Gov in one of the USGov regions and Office 365 in GCC DoD as the office data connectors are not supported in USGov.

**Comment by brandonconn03** [comment]
Thank you for the information @briandelmsft ! I'll take a look :) If I have any breakthroughs on the API I'll be sure to pass along.

**Comment by piaudonn** [comment]
@brandonconn03 were you able to give the new version of STAT a try? Like @briandelmsft mentionned, since you can customize URLS for all services, it should address your challenges.
