### ISSUE TITLE
[Feature] GrantPermissions - Fail if Connect-MgGraph or Login-AzAccount fail

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#429]
The GrantPermissions.ps1 PowerShell script should stop and return an error if the Connect-MgGraph or Login-AzAccount PowerShell cmdlets fail.  Currently the script will show an error but continue.

Let's add this for STAT v2

**Comment by piaudonn** [comment]
#430 that's a first try
