### ISSUE TITLE
[BUG] DeployPermissions.ps1

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#445]
There may be an issue with the newest versions of the PowerShell modules no longer working with the builtin PowerShell, now seem to only work with 7.

<img width="857" alt="image" src="https://github.com/briandelmsft/SentinelAutomationModules/assets/68655382/6723aaa1-92df-4114-8191-411a0328ba80">

**Comment by piaudonn** [comment]
I had a similar issue recently, but the customer and the customer had to update PowerShell to fix the problem.
I am not sure how we can address it in the script else than removing the dependency to the modules.
I was working on having a Graph API documented way to add permissions. Maybe a Postman package, or a raw level PowerShell workaround if we can't update PowerShell.

**Comment by briandelmsft** [comment]
@piaudonn what do you think about refining this to run from cloud shell?  Maybe the run a command in cloud shell to download and execute the script and it prompts for the tenantid, RG, etc.  then we document cloud shell as being the preferred way, though it should still work locally.  At least this way we have a consistent platform to run it from.

**Comment by piaudonn** [comment]
I gave it a first shot: 🔗 https://github.com/briandelmsft/SentinelAutomationModules/blob/445-bug-deploypermissionsps1/Deploy/GrantPermissions.ps1
