### ISSUE TITLE
Function Code Documentation

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#448]
If STAT is used in additional RGs from the install you'll be asked for the function code when building the first connection.  This should be documented in the wiki on how to get it

**Comment by piaudonn** [comment]
@briandelmsft  What do you think of this:

https://github.com/briandelmsft/SentinelAutomationModules/wiki/%E2%9D%93-FAQ#the-logic-app-designer-wants-the-function-code-to-use-statv2-how-can-i-get-this-code

**Comment by briandelmsft** [comment]
I think we should use the function specific key under 'modules' and not the main function app key, at least that's what we use in the connector by default... it probably doesn't matter though since it's not like there will be more than one function under this function app
