### ISSUE TITLE
[Feature] Add additional methods to MDE module

### ISSUE THREAD

**Issue by jujaakko** [briandelmsft/SentinelAutomationModules#452]
**Is your feature request related to a problem? Please describe.**
In some cases, a host-type entity in the incident does not contain either MDE ID or proper FQDN. As a result, the MDE module returns no results, even though the device (host) in the incident is onboarded to MDE.  An example, for which the MDE module doesn't return any information:

![image](https://github.com/briandelmsft/SentinelAutomationModules/assets/73217158/d319ff77-2f89-4127-816f-4000f379c976)

**Describe the solution you'd like**

The MDE module could obtain for example aadDeviceId using KQL (module) and fetch the information from the MDE API using this identifier. The KQL query could be something like this : 

DeviceInfo
| where AadDeviceId has "DeviceName" | project AadDeviceId | take 1

and the API call would be something like this:

https://api.securitycenter.microsoft.com/api/machines?$filter=aadDeviceId eq AadDeviceId

**Comment by briandelmsft** [comment]
Potential query to get all the host entities resolved in a single KQL, then just need to do some post processing the function to find the best match in the event of multiple matches for the same host

```kql
let hostEntities = datatable(FQDN:string, Hostname:string)['comp1.contoso.com','comp1','comp2.contoso.com','comp2'];
let FQDNs = hostEntities | project FQDN;
let Hostnames = hostEntities | project Hostname;
DeviceInfo
| where Timestamp > ago(14d)
| where DeviceName in~ (FQDNs) or DeviceName has_any (Hostnames)
| extend MatchType = iff(DeviceName in~ (FQDNs), 'FQDN', 'Hostname')
| summarize arg_max(Timestamp, *) by DeviceId
| project Timestamp, DeviceId, DeviceName, MatchType, AadDeviceId
```

**Comment by briandelmsft** [comment]
@piaudonn do you think we should provide an option to disable this enrichment via host name?

**Comment by jujaakko** [comment]
I agree, that would be a problem, this was just a first idea that came to me. Your logic sounds like a good option. 

Maybe one solution could be that if there's multiple devices with same name, just make the MDE API query for each of them and return all values? As a user, I think I'd rather have all the information at hand than no data at all. Though this might mess up with the scoring?

**Comment by briandelmsft** [comment]
@jujaakko I'll provide a link to the build and instructions early next week as soon as I've tested the build

**Comment by briandelmsft** [comment]
@jujaakko the build with this functionality is now published.  To update, simply repoint your function app to: `https://github.com/briandelmsft/STAT-Function/releases/download/v2.0.8/stat.zip`

To repoint the function app, locate the function app in the Azure portal and in the menu click 'Environment variables', click the variable WEBSITE_RUN_FROM_PACKAGE and change the value to `https://github.com/briandelmsft/STAT-Function/releases/download/v2.0.8/stat.zip`.  Click Apply and then restart the function app
