### ISSUE TITLE
STAT Deployment Issue

### ISSUE THREAD

**Issue by AminaAnjum** [briandelmsft/SentinelAutomationModules#460]
Hi Brian,

I am reaching out regarding an issue we are encountering with the deployment of Microsoft Sentinel modules using the SentinelAutomationModules. Specifically, we are not seeing all the required logic apps or playbooks deployed as expected.
 
We noticed that around 5 months ago, there were some changes made to the json file and now no playbooks or logic apps are being deployed as a result. We would like to know why these changes were made were there issues with the previous deployments. Is there any issue if we deploy from the legacy deploy option? Also, when we do deploy the latest version of STAT app we are unable to run it error free the Base module keeps failing giving the following error (bad request):

![bad request](https://github.com/user-attachments/assets/d36a0db2-f3dc-47cb-8bea-80563df950c7)

Could you please assist us in clarifying if there have been any updates or changes to the deployment process that we should be aware of? Any guidance on resolving the issues with manual deployment would also be greatly appreciated.
 
Thank you very much for your time and support.

**Comment by piaudonn** [comment]
The function based logic app (STAT version 2) is deploying the custom Logic App connector and a Azure Function App. It does not deploy multiple logic apps like it used to be. Make sure you are using the latest connectors in your playbooks if you are using the v2. You can still runt the v1, nothing has changed on that side and you can still find the legacy deployment here: https://github.com/briandelmsft/SentinelAutomationModules/tree/statv1.
Now for your specific error, we would need more info on how you call the v2 connector, maybe a screenshot or the code of the playbook calling STAT will help.

**Comment by briandelmsft** [comment]
@AminaAnjum do you have any updates based on Pierre's feedback?  Did you fix the problem?

The error is occurring when we're trying to determine if you started STAT from an incident or an alert (STAT v2 works with both).  The error indicates that whatever you are sending in doesn't support 'get' (it doesn't have properties).  Perhaps you are sending in the entities array?  In STAT v2 you need to send the entire body of the incident or alert.

**Comment by piaudonn** [comment]
Closing this as unresponsive. @AminaAnjum please let us know if you need assistance, we'll re-open it.
