### ISSUE TITLE
MDE Module - Simplify entities parsing

### ISSUE THREAD

**Issue by piaudonn** [briandelmsft/SentinelAutomationModules#49]
The current logic is very cumbersome. It can be redone with the foolowing assumption:
- There are nearly never account entities with only the aadUserId
- Most of account entities will have an AccountName

**Comment by piaudonn** [comment]
But we could make it a dependancy for the deployment, can't we? If it was already imported with the same version, then it will not reimport it (I think?). Or maybe the general strategy would be to deploy everything anyways.

**Comment by briandelmsft** [comment]
I think we would only ever deploy from the main deployment template so we would just need the parameter for the resourceId... If you did deploy a module directly then it would just be a matter of populating that string.
