### ISSUE TITLE
User assigned managed identity

### ISSUE THREAD

**Issue by briandelmsft** [briandelmsft/SentinelAutomationModules#58]
Should we switch to user assigned managed identity?  Sharing one identity across all the modules has some benefit in that it would simplify permissions assignment as the identity is shared but there could also be downsides.

**Comment by ThijsLecomte-TC** [comment]
I would like to give a +1 to User Assigned as this allows for an easier time in a CI/CD scenario!

**Comment by briandelmsft** [comment]
@ThijsLecomte-TC 

STAT v2 Preview is ready for you to try.  This is a major move forward from previous versions of STAT, now using an Azure Functions backend and Logic Apps front end.  The look and feel is the same as v1, but the improvements on the backend are substantial. This is also a complete rewrite of all of the backend functionality, so do be aware there may be some undiscovered bugs, though there are no known issues in this build.  If you encounter any bugs, or even unexpected changes in functionality from previous version please open an issue no matter how small the issue may be.

This build includes the following new features:

- Backend of STAT is now using Azure Functions instead of Logic apps
- Support for User Assigned Managed Identities, Service Principal and Multi Tenant service principal authentication (in addition to existing system assigned managed id support)
- Support for the Sentinel Alert trigger (in addition to existing incident trigger)
- Ability to create a new Sentinel incident from an alert and automatically link the alert
- Additional performance and other minor improvements

The Preview [deployment](https://github.com/briandelmsft/SentinelAutomationModules/tree/statv2_preview/Deploy) can be found only in the statv2_preview branch of this repo as well as supporting [documentation](https://github.com/briandelmsft/SentinelAutomationModules/blob/statv2_preview/Docs/). That includes documentation specific to [multi-tenant/MSSP](https://github.com/briandelmsft/SentinelAutomationModules/blob/statv2_preview/Docs/mssp.md) scenarios.

The main branch does not contain any information about v2 at this time, so ensure you select the correct branch.
