### ISSUE TITLE
FileInsight module

### ISSUE THREAD

**Issue by piaudonn** [briandelmsft/SentinelAutomationModules#85]
Leverage the FileProfile() function from Defender to return the prevalance of a file (as well as other meta data).

**Comment by briandelmsft** [comment]
Is there an opportunity here to integrate email attachments from the EmailAttachmentInfo table?

**Comment by piaudonn** [comment]
Absoluteley, we can return some mail info. Like if the hash or filename was found in an email, if so how many and a summary of the sender/recipient as well as first seen last seen.

**Comment by piaudonn** [comment]
Maybe we could have File support in the shared entities module.
To get the file name if a full path is poduced. maybe extract the extension too.

**Comment by briandelmsft** [comment]
Sure we could do that. 

Let's setup a time to talk this week and prioritze the work we have to do.  I'd like to work towards some beta release
